Sprint 1
belamov/ypgo-url-shortener pull request #1
Opened 2022-05-24 03:49 UTC by belamov

2022-05-30 11:05 UTC, belamov commented on internal/app/handlers/handlers_test.go
> +package handlers_test
пришлось так сделать, поскольку если оставить тут `package`, то компилятор будет ругаться на то, что в тестах запрещены циклические зависимости - пакет `server` импортит пакет `handlers`, а `server` мне нужен для того, чтобы замокать сервер. я не нашел другого способа исправить это

2022-05-30 20:15 UTC, ASPecherkin requested changes
Есть несколько замечаний

2022-05-30 20:15 UTC, ASPecherkin commented on .github/workflows/shortenertest.yml
> -      - name: "Code increment #4"
в целом можно не удалять/комментировать - по названию PR я понимаю какой инкремент должен быть последним проходящим и смотрю только до него 
аппрувнуть  PR я могу и с частью пройденных тестов

2022-05-30 20:15 UTC, ASPecherkin commented on internal/app/config/config.go
> +func Port() string {
лучше назвать GetPort/GetHost - 
Port, Host обычно называют поля структуры
в функции нужно лучше обозначить выполняемое дейстие

2022-05-30 20:15 UTC, ASPecherkin commented on internal/app/handlers/handlers.go
> +	"github.com/belamov/ypgo-url-shortener/internal/app/services"
стилистический комментарий 
в каждой компании или репозитории в Go есть принятый стиль сортировки пакетов в импортах 
Чаще всего это 
stdlib
пакеты приложения
внешние зависимости

Это можно получить путём установки и настройки в IDE комбинации https://golangci-lint.run/usage/install/  и goimports

2022-05-30 20:15 UTC, ASPecherkin commented on internal/app/handlers/handlers_test.go
> +package handlers_test
Кажется ты можешь это развязать следующим спсобом - вынести конструктор Chi в отдельный пакет ( может быть прямо к handlers) и уже полученный роутер использовать как зависимость для сервера 
и тогда единственное место вызова сервера тут 
```go
s := server.New(cfg, service)
r := s.NewRouter()
```
тебе непонадобится, так как роутер ты получишь из его конкретного конструктора

2022-05-30 20:15 UTC, ASPecherkin commented on internal/app/storage/in_memory_repository.go
> +type storage map[string]string
этого нет в описании курса, но есть в использовании map в качестве хранилища 
если будет конкуретная запись ( а она здесь возможна), то будет паника приложения 
подробнее можно прочитать тут - https://medium.com/@luanrubensf/concurrent-map-access-in-go-a6a733c5ffd1

2022-05-30 20:22 UTC, belamov commented on .github/workflows/shortenertest.yml
> -      - name: "Code increment #4"
я могу раскоментировать, но мне так удобнее - видя зеленую галочку, я понимаю, что все ок, не приходится заходить вовнутрь воркфлоу, плюс оповещения об ошибках в пайплайне не приходят, можно оставить так?)

2022-05-30 23:07 UTC, belamov commented on .github/workflows/shortenertest.yml
> -      - name: "Code increment #4"
буду активировать те тесты, инкременты которых я сейчас выполняю

2022-06-01 08:50 UTC, ASPecherkin commented on .github/workflows/shortenertest.yml
> -      - name: "Code increment #4"
Да, давай так - мне не принципильно

2022-06-01 08:52 UTC, ASPecherkin approved these changes
Всё хорошо, замечания исправлены - принимаю работу

2022-06-01 08:57 UTC, merged