sprint 2
belamov/ypgo-url-shortener pull request #2
Opened 2022-06-10 17:07 UTC by belamov

2022-06-15 21:46 UTC, belamov commented on internal/app/config/config.go
> +func (c *Config) Init() {
как можно это протестировать? например, я хочу убедиться, что при отсутствии флага используется значение переменной окружения. либо просто убедиться, что конфиг собирается и из флагов, и из переменных окружения корректно. не нашел способа это в юнит тестах сделать, видимо нужно как-то билдить и запускать с различными аргументами, но я не пойму, как это можно автоматизировать. писать сложный make файл?

2022-06-16 12:36 UTC, ASPecherkin requested changes
Есть небольшие замечания + ответ на вопрос , передаю работу обратно

2022-06-16 12:36 UTC, ASPecherkin commented on internal/app/config/config.go
> +func (c *Config) Init() {
смотри - передачу флагов из cli и не тестируют, именно факт передачи 
но ты можешь сделать Init() , который уже вернёт/соберёт объект Config в котором уже будут проставлены нужные значения 
если хочешь проверить работу по-умлчанию и вычитывание из env - можешь их и проставить в рамках подготовки к тесту 

кажется это то, что ты у меня хотел узнать 
Но итог - не тестируй передачу cli флагов, проставь значения env в тестах и (SetEnv , кажется функция) и проверяй что будет в структуре config после вызова Init

2022-06-16 12:36 UTC, ASPecherkin commented on internal/app/handlers/handlers.go
> +	} else {
здесь else можно опустить, так как у тебя есть выход в случае gzip , а других вариатов нет

2022-06-16 12:36 UTC, ASPecherkin commented on internal/app/storage/file_repository.go
> +	err := repo.file.Close()
можно просто 
```go
return repo.file.Close()
```

2022-06-16 17:16 UTC, belamov commented on internal/app/config/config.go
> +func (c *Config) Init() {
@ASPecherkin понял, спасибо) просто автотесты это тестируют, но они билдят в ci бинарник и запускают его, думал, что можно как-то несложно это покрыть тестами)

2022-06-18 20:34 UTC, ASPecherkin approved these changes
Принимаю работу

2022-06-18 20:34 UTC, ASPecherkin commented on internal/app/storage/file_repository.go
> +		mutex:   sync.RWMutex{},
стилистическое и может помочь в будущем - лучше использовать укатель на mutex и записывать new(sync.Rwmutex) 
но здесь это рабочий вариант, потому что ты везде работаешь с FileRepository по указателю

2022-06-18 20:51 UTC, merged